# Generated by Django 3.2.9 on 2021-11-06 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('degrees', '0002_alter_degree_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
                ('id_career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belonging_degree', to='degrees.degree')),
            ],
        ),
    ]
