# Generated by Django 3.2.6 on 2021-11-15 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0002_alter_degree_name'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='id_career',
            new_name='id_degree',
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('id_degree', 'subject_name')},
        ),
    ]
