# Generated by Django 3.2.9 on 2021-11-06 20:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('degrees', '0002_alter_degree_name'),
        ('users_degrees', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdegree',
            unique_together={('id_user', 'id_degree')},
        ),
    ]
