# Generated by Django 3.2.9 on 2021-11-06 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlative_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlative_subject', to='subjects.subject')),
                ('id_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_subject', to='subjects.subject')),
            ],
            options={
                'unique_together': {('id_subject', 'correlative_subject')},
            },
        ),
    ]
